project_id = "jaoxormsyftctpsegtza"

[functions.uazapi-proxy]
enabled = true
verify_jwt = false
import_map = "./functions/uazapi-proxy/deno.json"
entrypoint = "./functions/uazapi-proxy/index.ts"

[functions.disparo-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/disparo-webhook/index.ts"

[functions.disparo-cron]
enabled = true
verify_jwt = false
entrypoint = "./functions/disparo-cron/index.ts"

[functions.stories-cron]
enabled = true
verify_jwt = false
entrypoint = "./functions/stories-cron/index.ts"
